<?php

return [
    'online' => 'Online',
    'offline' => 'Offline',
    'starting' => 'Aan het opstarten',
    'stopping' => 'Bezig met stoppen',
    'suspended' => 'Opgeschort',
    'connection-error' => 'Fout bij de verbinding',
    'transferring' => 'Bezig met overzetten',
    'installing' => 'Installeren',
    'restoring-backup' => 'Back-Up Terugzetten',
    'unavailable' => 'Onbereikbaar',
    'status' => 'Status',
    'CPU' => 'CPU',
    'memory' => 'Geheugen',
    'disk' => 'Schijf',
    'unlimited' => 'Onbeperkt',
    'start' => 'Start',
    'restart' => 'Herstart',
    'stop' => 'Stop',
    'kill' => 'Kill',
    'forcibly-stop-process' => 'Forcibly Stop Process',
    'continue' => 'Doorgaan',
    'forcibly-stopping-alert' => 'Forcibly stopping a server can lead to data corruption.',
    'cpu-usage' => 'CPU-gebruik',
    'memory-usage' => 'Geheugengebruik',
    'disk-usage' => 'Disk Usage',
    'inbound-outbound' => 'Inbound / Outbound',
    'low-resources' => 'Low on resources',
    'low-resources-desc' => 'Your server is running low on resources, make sure to upgrade your plan',
    'upgrade-server' => 'Server Upgraden',
    'cancel' => 'Annuleer',
    'copied-text' => '{{text}} gekopieerd naar klembord.',
    'showing' => 'Showing',
    'to' => 'to',
    'of' => 'of',
    'results' => 'results.',
];
